# Generated by Django 5.2.16 on 2026-07-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date du repas')),
                ('plat_principal', models.CharField(max_length=200, verbose_name='plat principal')),
                ('description', models.TextField(blank=True, verbose_name='description / accompagnements')),
                ('prix_cents', models.IntegerField(help_text="Prix du repas en centimes d'euro.", verbose_name='prix (centimes)')),
                ('ferme_a', models.DateTimeField(help_text='Date et heure limites pour réserver ce menu.', verbose_name='clôture des réservations')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProfilParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('solde_cents', models.IntegerField(default=0, help_text="Solde du parent en centimes d'euro (crédité aux paiements validés).", verbose_name='solde (centimes)')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_parent', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil parent',
                'verbose_name_plural': 'profils parents',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_cents', models.IntegerField(help_text="Montant du virement déclaré, en centimes d'euro.", verbose_name='montant (centimes)')),
                ('reference_virement', models.CharField(help_text='Communication libre ou structurée indiquée sur le virement.', max_length=100, verbose_name='référence du virement')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='date de déclaration')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='declare', max_length=20, verbose_name='statut')),
                ('commentaire_compta', models.TextField(blank=True, verbose_name='commentaire compta')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='cantine.profilparent', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('allergies', models.TextField(blank=True, help_text='Renseigné librement par le parent.', verbose_name='allergies / régime')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='cantine.classe', verbose_name='classe')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='cantine.profilparent', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'enfant',
                'verbose_name_plural': 'enfants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('presence_matin_ok', 'Présence matin confirmée'), ('mangee', 'Mangée'), ('annulee', 'Annulée')], default='en_attente_paiement', max_length=30, verbose_name='statut')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='date de réservation')),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cantine.enfant', verbose_name='enfant')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cantine.menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-menu__date'],
                'unique_together': {('enfant', 'menu')},
            },
        ),
    ]
