# Generated by Django 5.2.16 on 2026-07-13 16:42

from django.db import migrations, models


def copier_prix_existants(apps, schema_editor):
    """Recopie l'ancien `prix_cents` vers les nouveaux champs.

    Hypothèses raisonnables :
      - `prix_primaire_cents` et `prix_maternelle_cents` reprennent
        la valeur historique (à ajuster manuellement ensuite).
      - `prix_potage_cents` est fixé à la moitié du prix primaire
        (arrondi à l'entier de centime le plus proche).
      - `prix_adulte_cents` est fixé à 1,5 fois le prix primaire.
    """
    Menu = apps.get_model("cantine", "Menu")
    for menu in Menu.objects.all():
        ancien = menu.prix_cents or 0
        menu.prix_maternelle_cents = ancien
        menu.prix_primaire_cents = ancien
        menu.prix_potage_cents = round(ancien / 2)
        menu.prix_adulte_cents = round(ancien * 1.5)
        menu.save(update_fields=[
            "prix_maternelle_cents",
            "prix_primaire_cents",
            "prix_potage_cents",
            "prix_adulte_cents",
        ])


def rollback_copier_prix_existants(apps, schema_editor):
    """Inverse : remet les nouveaux champs à 0 (rollback simple).

    Le champ `prix_cents` d'origine n'est pas restauré : la migration
    inverse d'`AlterField` fera son travail sur le schéma.
    """
    Menu = apps.get_model("cantine", "Menu")
    Menu.objects.update(
        prix_maternelle_cents=0,
        prix_primaire_cents=0,
        prix_potage_cents=0,
        prix_adulte_cents=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cantine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire')], default='primaire', help_text='Détermine le tarif applicable aux enfants de cette classe.', max_length=20, verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='menu',
            name='prix_adulte_cents',
            field=models.IntegerField(default=0, help_text='Prix du repas pour un adulte (personnel/enseignants). Réservé à un usage futur.', verbose_name='prix adulte (centimes)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='prix_maternelle_cents',
            field=models.IntegerField(default=0, help_text='Prix du repas complet pour un enfant de maternelle.', verbose_name='prix maternelle (centimes)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='prix_potage_cents',
            field=models.IntegerField(default=0, help_text='Prix de la formule « potage seul », identique pour tous.', verbose_name='prix potage (centimes)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='prix_primaire_cents',
            field=models.IntegerField(default=0, help_text='Prix du repas complet pour un enfant de primaire.', verbose_name='prix primaire (centimes)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='formule',
            field=models.CharField(choices=[('complet', 'Repas complet'), ('potage', 'Potage seul')], default='complet', help_text='Repas complet ou potage seul (choisi à la réservation).', max_length=20, verbose_name='formule'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='prix_cents',
            field=models.IntegerField(blank=True, help_text='Champ conservé temporairement pour la migration ; supprimé par une migration ultérieure. Utiliser les champs prix_*_cents.', null=True, verbose_name='prix (centimes) — obsolète'),
        ),
        migrations.RunPython(
            copier_prix_existants,
            reverse_code=rollback_copier_prix_existants,
        ),
    ]
