# Generated by Django 5.2.16 on 2026-07-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantine', '0002_ajout_niveau_prix_formule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='prix_cents',
        ),
    ]
